zeppelin:
  image: mielhostens/bovi-analytics
  environment:
    ZEPPELIN_PORT: 8080
    #ZEPPELIN_JAVA_OPTS: >-
    #  -Dspark.driver.memory=2g
    #  -Dspark.executor.memory=4g
    MASTER: local[*]
  ports:
    - 8080:8080
    - 4040:4040
  volumes:
    - ./data:/usr/zeppelin/data
    - ./notebooks:/usr/zeppelin/notebook
